name: robo-claim-directory
services:
  # Configuration for Service Mocking
  postgres:
    image: postgres:15 # should match version in AWS RDS
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGPORT: ${POSTGRES_PORT}
      PGDBNAME: ${POSTGRES_NAME}
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_database:
